# Generated by Django 4.2.23 on 2025-08-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('vehicle', 'Vehicle'), ('equipment', 'Equipment')], max_length=20)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, upload_to='products/')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
