# Generated by Django 4.2.23 on 2025-08-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6),
        ),
    ]
